# Base image: Ubuntu 22.04
FROM ubuntu:22.04 

# Update packages and install git, cmake, and build-essential
RUN apt-get update && apt-get install -y git cmake build-essential

# Clone MMseqs2 repository and checkout version 14
RUN git clone https://github.com/soedinglab/MMseqs2.git \
    && cd MMseqs2 \
    && git checkout 7e2840992948ee89dcc336522dc98a74fe0adf00 \
    && mkdir build \
    && cd build \
    && cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. .. \
    && make \
    && make install 

# Add MMseqs2 binaries to the PATH
ENV PATH="/MMseqs2/build/bin/:${PATH}"

# docker build -t mmseqs:v14 .
# docker run -v mmseqs --entrypoint bash -i -t mmseqs:v14